set -g prefix `
unbind C-b
bind ` send-prefix

set -g mouse on

# Necessary for some events like Vim's autoread
set -g focus-events on

# index only matters for keyboard shortcuts, and 1 is at the left of kb
set -g base-index 1

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{plane_current_path}"

set -g main-pane-width 75%

set -as terminal-features ",xterm-256color:focus"
set -as terminal-features ",xterm-ghostty:extkeys"

set -g default-terminal "xterm-ghostty"

bind-key , command-prompt "rename-window -- '%%'"
bind-key $ command-prompt "rename-session -- '%%'"

set -sg escape-time 0

set -g mode-keys vi

bind-key -T copy-mode-vi WheelUpPane select-pane \; send-keys -X -N 2 scroll-up
bind-key -T copy-mode-vi WheelDownPane select-pane \; send-keys -X -N 2 scroll-down

bind-key -T prefix s swap-pane -t 0

bind -n M-` if-shell -F '#{==:{@bt_prefix},off}' \
  'set -g prefix `; set -g @bt_prefix on; set -g status-right "prefix: ON "' \
  'set -g prefix None; set -g @bt_prefix off; set -g status-right "prefix: OFF"'
set -g @bt_prefix on

